### PR TITLE
Milestone 3: Feature game logic

### PR DESCRIPTION
**Pull request by joshuaoivie**
Dear Code Reviewer,

Thank you for taking the time to review our project. The pull request contains the following changes: 

- game logic required to determine a win
- game logic to determine a draw
- text format for terminal

We're looking forward to your objective review.

Warm Regards,
Josh

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:
However, there are some changes that you need to make in order to get your project approved

- [x] user input should be validated so it's not empty. ( users should not be able to create an empty username)
  Kindly add a function that will check if the user input is not empty, otherwise ask the user to enter a valid user name )

- [x] The filename and module name should be the same. eg. the GameLogic module should have game_logic.rb naming 

- [x] In the Game class you have ```attr_reader :player_one, :player_two, :active_player```, but you are not using those accessors.

- [x] Please don't change any rubocop rules


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The game runs as expected
    

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Validate the user input for usernames so that neither empty usernames are accepted nor does the game terminate due to an error. I'm getting this error for empty usernames.
```
bin/main.rb:44:in `store_name': wrong number of arguments (given 0, expected 1) (ArgumentError)
``` 

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

**Congratulations and good job.** :+1: :clap: 

**Thank you for implementing the changes from the previous reviews.**

**I liked the way you listed the remaining available spots(numbers) on the board for players to choose from.**

**You may go ahead and merge this branch.**

**I wish you good luck with your future projects.**

**Cheers and happy coding.** :desktop_computer: :+1:

**Comment by joshuaoivie** [comment]
Thank you so much for your reviews @MkrtichSargsyan, @mke2111 and @george-shammar!

**Pull request merged**
